image: 
 # name: "dbisilm/alpine-clang-boost:latest"
  name: "alpine-clang-boost/mac"
  entrypoint: [ '/bin/sh', '-c' ]

stages:
  - build
  - test

build:
  stage: build
  tags:
    - grouprunner
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PMDK=OFF -DUSE_LLVM=OFF -DLLVM_DIR=/usr/lib/cmake/llvm16 ..
    - make -j 3
    # clean up unnecessary files and strip binaries
    - strip test/*_test
  artifacts:
    paths:
      - build
    expire_in: 30 minutes

test:
  stage: test
  tags:
    - grouprunner
  script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PMDK=OFF -DUSE_LLVM=OFF -DLLVM_DIR=/usr/lib/cmake/llvm16 ..
    - make -j 3
    - ctest --output-on-failure
  dependencies:
    - build
