image: 
  name: "dbisilm/llvm_pmdk:clang"
  entrypoint: [ '/bin/sh', '-c' ]

stages:
  - build
  - test

build:
  stage: build
  tags:
    - grouprunner
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_PMDK=OFF -DLLVM_DIR=/usr/lib64/cmake/llvm ..
    - make -j 3
    # clean up unnecessary files and strip binaries
    - rm -rf _deps 
    - strip test/*_test
  artifacts:
    paths:
      - build/
    expire_in: 30 minutes

test:
  stage: test
  tags:
    - grouprunner
  script:
    - pip install pytest --user
    - cd build
    - ctest --output-on-failure